### ISSUE TITLE
Create a complete compile guide for linux

### ISSUE THREAD

**Issue by lfxgroove** [mangoswiki/Wiki#2]
Current one isn't finished, this should be done, placed here as a reminder

**Comment by billy1arm** [comment]
Hi All, missed this as I normally check the forum for issues.

MangosThree is currently being reworked to use the new build system - so check out the develop21 branch.

mlib is replaced in mangosThree and Four by stormlib since mlib cannot read the new format dbc's correctly.

@LordJimBeam - I would appreciate you looking over the new build system files to see whether you change is still required.

Thanks to you all

**Comment by gabryatfendor** [comment]
Yesterday I was finally able to compile and run mangos-zero on Ubuntu 15.04. I'm gonna rewrite Linux installation guide for branch, since is not very clear (even less for branche develop21, which is the active now).

**Comment by billy1arm** [comment]
@gabryatfendor - tyvm
